using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "6cf0c346f8d7e03b")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.2")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1048 with alias "seoDocType"
	/// <summary>SeoDocType</summary>
	public partial interface ISeoDocType : IPublishedContent
	{
		/// <summary>Tarayıcı Başlığı</summary>
		string BrowserTitle { get; }

		/// <summary>Meta Tanımlama</summary>
		string MetaDescription { get; }

		/// <summary>Etiketler</summary>
		object MetaTags { get; }
	}

	/// <summary>SeoDocType</summary>
	[PublishedContentModel("seoDocType")]
	public partial class SeoDocType : PublishedContentModel, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "seoDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SeoDocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SeoDocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return GetBrowserTitle(this); }
		}

		/// <summary>Static getter for Tarayıcı Başlığı</summary>
		public static string GetBrowserTitle(ISeoDocType that) { return that.GetPropertyValue<string>("browserTitle"); }

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return GetMetaDescription(this); }
		}

		/// <summary>Static getter for Meta Tanımlama</summary>
		public static string GetMetaDescription(ISeoDocType that) { return that.GetPropertyValue<string>("metaDescription"); }

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return GetMetaTags(this); }
		}

		/// <summary>Static getter for Etiketler</summary>
		public static object GetMetaTags(ISeoDocType that) { return that.GetPropertyValue("metaTags"); }
	}

	// Mixin content Type 1057 with alias "baseContentDocType"
	/// <summary>BaseContentDocType</summary>
	public partial interface IBaseContentDocType : IPublishedContent
	{
		/// <summary>İçerik</summary>
		IHtmlString ContentText { get; }

		/// <summary>Listelenecek Komşular Ögesi</summary>
		object NeighbourWidgetRoot { get; }

		/// <summary>Banner</summary>
		object PageBanner { get; }

		/// <summary>Sayfa Resmi</summary>
		object PageImage { get; }

		/// <summary>Yayınlama Tarihi</summary>
		DateTime PagePublishDate { get; }

		/// <summary>Alt başlık</summary>
		string PageSubTitle { get; }

		/// <summary>Sayfa Başlığı</summary>
		string PageTitle { get; }

		/// <summary>Önyazı</summary>
		string PreviewText { get; }

		/// <summary>Yönlendirme</summary>
		object UmbracoRedirect { get; }
	}

	/// <summary>BaseContentDocType</summary>
	[PublishedContentModel("baseContentDocType")]
	public partial class BaseContentDocType : PublishedContentModel, IBaseContentDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baseContentDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BaseContentDocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseContentDocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return GetContentText(this); }
		}

		/// <summary>Static getter for İçerik</summary>
		public static IHtmlString GetContentText(IBaseContentDocType that) { return that.GetPropertyValue<IHtmlString>("contentText"); }

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return GetNeighbourWidgetRoot(this); }
		}

		/// <summary>Static getter for Listelenecek Komşular Ögesi</summary>
		public static object GetNeighbourWidgetRoot(IBaseContentDocType that) { return that.GetPropertyValue("neighbourWidgetRoot"); }

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return GetPageBanner(this); }
		}

		/// <summary>Static getter for Banner</summary>
		public static object GetPageBanner(IBaseContentDocType that) { return that.GetPropertyValue("pageBanner"); }

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return GetPageImage(this); }
		}

		/// <summary>Static getter for Sayfa Resmi</summary>
		public static object GetPageImage(IBaseContentDocType that) { return that.GetPropertyValue("pageImage"); }

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return GetPagePublishDate(this); }
		}

		/// <summary>Static getter for Yayınlama Tarihi</summary>
		public static DateTime GetPagePublishDate(IBaseContentDocType that) { return that.GetPropertyValue<DateTime>("pagePublishDate"); }

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return GetPageSubTitle(this); }
		}

		/// <summary>Static getter for Alt başlık</summary>
		public static string GetPageSubTitle(IBaseContentDocType that) { return that.GetPropertyValue<string>("pageSubTitle"); }

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return GetPageTitle(this); }
		}

		/// <summary>Static getter for Sayfa Başlığı</summary>
		public static string GetPageTitle(IBaseContentDocType that) { return that.GetPropertyValue<string>("pageTitle"); }

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return GetPreviewText(this); }
		}

		/// <summary>Static getter for Önyazı</summary>
		public static string GetPreviewText(IBaseContentDocType that) { return that.GetPropertyValue<string>("previewText"); }

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return GetUmbracoRedirect(this); }
		}

		/// <summary>Static getter for Yönlendirme</summary>
		public static object GetUmbracoRedirect(IBaseContentDocType that) { return that.GetPropertyValue("umbracoRedirect"); }
	}

	/// <summary>Site</summary>
	[PublishedContentModel("site")]
	public partial class Site : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "site";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Site(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Site, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// #TrackingCode
		///</summary>
		[ImplementPropertyType("trackingCode")]
		public string TrackingCode
		{
			get { return this.GetPropertyValue<string>("trackingCode"); }
		}

		///<summary>
		/// #DocTypeFieldBaseSite
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return this.GetPropertyValue("umbracoRedirect"); }
		}
	}

	// Mixin content Type 1060 with alias "homePageItem"
	/// <summary>HomePage Base</summary>
	public partial interface IHomePageItem : IPublishedContent
	{
		/// <summary>Şehir</summary>
		string AddressCity { get; }

		/// <summary>Adres Satırı - 1</summary>
		string AddressLine1 { get; }

		/// <summary>Adres Satırı - 2</summary>
		string AddressLine2 { get; }

		/// <summary>E-posta</summary>
		string ContactEmail { get; }

		/// <summary>Google Maps</summary>
		string ContactGoogleMaps { get; }

		/// <summary>Mobil Telefon</summary>
		string ContactMobilePhone { get; }

		/// <summary>Telefon</summary>
		string ContactPhone { get; }

		/// <summary>Footer Bağlantıları</summary>
		string FooterLinks { get; }

		/// <summary>Site Menüsü</summary>
		object SiteMenu { get; }

		/// <summary>Facebook</summary>
		string SocialFacebook { get; }

		/// <summary>Google+</summary>
		string SocialGooglePlus { get; }

		/// <summary>Instagram</summary>
		string SocialInstagram { get; }

		/// <summary>Twitter</summary>
		string SocialTwitter { get; }
	}

	/// <summary>HomePage Base</summary>
	[PublishedContentModel("homePageItem")]
	public partial class HomePageItem : PublishedContentModel, IHomePageItem
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePageItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePageItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePageItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Şehir
		///</summary>
		[ImplementPropertyType("addressCity")]
		public string AddressCity
		{
			get { return GetAddressCity(this); }
		}

		/// <summary>Static getter for Şehir</summary>
		public static string GetAddressCity(IHomePageItem that) { return that.GetPropertyValue<string>("addressCity"); }

		///<summary>
		/// Adres Satırı - 1
		///</summary>
		[ImplementPropertyType("addressLine1")]
		public string AddressLine1
		{
			get { return GetAddressLine1(this); }
		}

		/// <summary>Static getter for Adres Satırı - 1</summary>
		public static string GetAddressLine1(IHomePageItem that) { return that.GetPropertyValue<string>("addressLine1"); }

		///<summary>
		/// Adres Satırı - 2
		///</summary>
		[ImplementPropertyType("addressLine2")]
		public string AddressLine2
		{
			get { return GetAddressLine2(this); }
		}

		/// <summary>Static getter for Adres Satırı - 2</summary>
		public static string GetAddressLine2(IHomePageItem that) { return that.GetPropertyValue<string>("addressLine2"); }

		///<summary>
		/// E-posta
		///</summary>
		[ImplementPropertyType("contactEmail")]
		public string ContactEmail
		{
			get { return GetContactEmail(this); }
		}

		/// <summary>Static getter for E-posta</summary>
		public static string GetContactEmail(IHomePageItem that) { return that.GetPropertyValue<string>("contactEmail"); }

		///<summary>
		/// Google Maps
		///</summary>
		[ImplementPropertyType("contactGoogleMaps")]
		public string ContactGoogleMaps
		{
			get { return GetContactGoogleMaps(this); }
		}

		/// <summary>Static getter for Google Maps</summary>
		public static string GetContactGoogleMaps(IHomePageItem that) { return that.GetPropertyValue<string>("contactGoogleMaps"); }

		///<summary>
		/// Mobil Telefon
		///</summary>
		[ImplementPropertyType("contactMobilePhone")]
		public string ContactMobilePhone
		{
			get { return GetContactMobilePhone(this); }
		}

		/// <summary>Static getter for Mobil Telefon</summary>
		public static string GetContactMobilePhone(IHomePageItem that) { return that.GetPropertyValue<string>("contactMobilePhone"); }

		///<summary>
		/// Telefon
		///</summary>
		[ImplementPropertyType("contactPhone")]
		public string ContactPhone
		{
			get { return GetContactPhone(this); }
		}

		/// <summary>Static getter for Telefon</summary>
		public static string GetContactPhone(IHomePageItem that) { return that.GetPropertyValue<string>("contactPhone"); }

		///<summary>
		/// Footer Bağlantıları
		///</summary>
		[ImplementPropertyType("footerLinks")]
		public string FooterLinks
		{
			get { return GetFooterLinks(this); }
		}

		/// <summary>Static getter for Footer Bağlantıları</summary>
		public static string GetFooterLinks(IHomePageItem that) { return that.GetPropertyValue<string>("footerLinks"); }

		///<summary>
		/// Site Menüsü
		///</summary>
		[ImplementPropertyType("siteMenu")]
		public object SiteMenu
		{
			get { return GetSiteMenu(this); }
		}

		/// <summary>Static getter for Site Menüsü</summary>
		public static object GetSiteMenu(IHomePageItem that) { return that.GetPropertyValue("siteMenu"); }

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("socialFacebook")]
		public string SocialFacebook
		{
			get { return GetSocialFacebook(this); }
		}

		/// <summary>Static getter for Facebook</summary>
		public static string GetSocialFacebook(IHomePageItem that) { return that.GetPropertyValue<string>("socialFacebook"); }

		///<summary>
		/// Google+
		///</summary>
		[ImplementPropertyType("socialGooglePlus")]
		public string SocialGooglePlus
		{
			get { return GetSocialGooglePlus(this); }
		}

		/// <summary>Static getter for Google+</summary>
		public static string GetSocialGooglePlus(IHomePageItem that) { return that.GetPropertyValue<string>("socialGooglePlus"); }

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("socialInstagram")]
		public string SocialInstagram
		{
			get { return GetSocialInstagram(this); }
		}

		/// <summary>Static getter for Instagram</summary>
		public static string GetSocialInstagram(IHomePageItem that) { return that.GetPropertyValue<string>("socialInstagram"); }

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("socialTwitter")]
		public string SocialTwitter
		{
			get { return GetSocialTwitter(this); }
		}

		/// <summary>Static getter for Twitter</summary>
		public static string GetSocialTwitter(IHomePageItem that) { return that.GetPropertyValue<string>("socialTwitter"); }
	}

	// Mixin content Type 1065 with alias "galleryFolderDocType"
	/// <summary>Galeri</summary>
	public partial interface IGalleryFolderDocType : IPublishedContent
	{
	}

	/// <summary>Galeri</summary>
	[PublishedContentModel("galleryFolderDocType")]
	public partial class GalleryFolderDocType : PublishedContentModel, IGalleryFolderDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "galleryFolderDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GalleryFolderDocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GalleryFolderDocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Görsel</summary>
	[PublishedContentModel("galleryItemDocType")]
	public partial class GalleryItemDocType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "galleryItemDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GalleryItemDocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GalleryItemDocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Açıklama
		///</summary>
		[ImplementPropertyType("galleryImageDescription")]
		public string GalleryImageDescription
		{
			get { return this.GetPropertyValue<string>("galleryImageDescription"); }
		}

		///<summary>
		/// Dosya
		///</summary>
		[ImplementPropertyType("galleryImageFile")]
		public Umbraco.Web.Models.ImageCropDataSet GalleryImageFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("galleryImageFile"); }
		}

		///<summary>
		/// Başlık
		///</summary>
		[ImplementPropertyType("galleryImageTitle")]
		public string GalleryImageTitle
		{
			get { return this.GetPropertyValue<string>("galleryImageTitle"); }
		}
	}

	/// <summary>SitemapDocumentType</summary>
	[PublishedContentModel("sitemapDocumentType")]
	public partial class SitemapDocumentType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sitemapDocumentType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SitemapDocumentType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SitemapDocumentType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Ana Sayfa</summary>
	[PublishedContentModel("clientHome")]
	public partial class ClientHome : PublishedContentModel, IHomePageItem, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "clientHome";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ClientHome(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ClientHome, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hakkımızda
		///</summary>
		[ImplementPropertyType("aboutPage")]
		public object AboutPage
		{
			get { return this.GetPropertyValue("aboutPage"); }
		}

		///<summary>
		/// Faks
		///</summary>
		[ImplementPropertyType("contactFax")]
		public string ContactFax
		{
			get { return this.GetPropertyValue<string>("contactFax"); }
		}

		///<summary>
		/// hakkimidabuton
		///</summary>
		[ImplementPropertyType("hakkimidabuton")]
		public string Hakkimidabuton
		{
			get { return this.GetPropertyValue<string>("hakkimidabuton"); }
		}

		///<summary>
		/// hakkimizdaResim
		///</summary>
		[ImplementPropertyType("hakkimizdaResim")]
		public object HakkimizdaResim
		{
			get { return this.GetPropertyValue("hakkimizdaResim"); }
		}

		///<summary>
		/// Site Başlığı
		///</summary>
		[ImplementPropertyType("homePageTitle")]
		public string HomePageTitle
		{
			get { return this.GetPropertyValue<string>("homePageTitle"); }
		}

		///<summary>
		/// Kategori
		///</summary>
		[ImplementPropertyType("kategorigetir")]
		public object Kategorigetir
		{
			get { return this.GetPropertyValue("kategorigetir"); }
		}

		///<summary>
		/// ortaResim
		///</summary>
		[ImplementPropertyType("ortaResim")]
		public object OrtaResim
		{
			get { return this.GetPropertyValue("ortaResim"); }
		}

		///<summary>
		/// Projeler
		///</summary>
		[ImplementPropertyType("projectHighlites")]
		public string ProjectHighlites
		{
			get { return this.GetPropertyValue<string>("projectHighlites"); }
		}

		///<summary>
		/// projeLink
		///</summary>
		[ImplementPropertyType("projeLink")]
		public object ProjeLink
		{
			get { return this.GetPropertyValue("projeLink"); }
		}

		///<summary>
		/// projesurecbaslik
		///</summary>
		[ImplementPropertyType("projesurecbaslik")]
		public string Projesurecbaslik
		{
			get { return this.GetPropertyValue<string>("projesurecbaslik"); }
		}

		///<summary>
		/// projeyonetimbaslik
		///</summary>
		[ImplementPropertyType("projeyonetimbaslik")]
		public string Projeyonetimbaslik
		{
			get { return this.GetPropertyValue<string>("projeyonetimbaslik"); }
		}

		///<summary>
		/// Slider Galeri
		///</summary>
		[ImplementPropertyType("sliderGallery")]
		public object SliderGallery
		{
			get { return this.GetPropertyValue("sliderGallery"); }
		}

		///<summary>
		/// sonprojelerbaslik
		///</summary>
		[ImplementPropertyType("sonprojelerbaslik")]
		public string Sonprojelerbaslik
		{
			get { return this.GetPropertyValue<string>("sonprojelerbaslik"); }
		}

		///<summary>
		/// tumprojelerbuton
		///</summary>
		[ImplementPropertyType("tumprojelerbuton")]
		public string Tumprojelerbuton
		{
			get { return this.GetPropertyValue<string>("tumprojelerbuton"); }
		}

		///<summary>
		/// ustBaslik
		///</summary>
		[ImplementPropertyType("ustBaslik")]
		public string UstBaslik
		{
			get { return this.GetPropertyValue<string>("ustBaslik"); }
		}

		///<summary>
		/// Şehir
		///</summary>
		[ImplementPropertyType("addressCity")]
		public string AddressCity
		{
			get { return HomePageItem.GetAddressCity(this); }
		}

		///<summary>
		/// Adres Satırı - 1
		///</summary>
		[ImplementPropertyType("addressLine1")]
		public string AddressLine1
		{
			get { return HomePageItem.GetAddressLine1(this); }
		}

		///<summary>
		/// Adres Satırı - 2
		///</summary>
		[ImplementPropertyType("addressLine2")]
		public string AddressLine2
		{
			get { return HomePageItem.GetAddressLine2(this); }
		}

		///<summary>
		/// E-posta
		///</summary>
		[ImplementPropertyType("contactEmail")]
		public string ContactEmail
		{
			get { return HomePageItem.GetContactEmail(this); }
		}

		///<summary>
		/// Google Maps
		///</summary>
		[ImplementPropertyType("contactGoogleMaps")]
		public string ContactGoogleMaps
		{
			get { return HomePageItem.GetContactGoogleMaps(this); }
		}

		///<summary>
		/// Mobil Telefon
		///</summary>
		[ImplementPropertyType("contactMobilePhone")]
		public string ContactMobilePhone
		{
			get { return HomePageItem.GetContactMobilePhone(this); }
		}

		///<summary>
		/// Telefon
		///</summary>
		[ImplementPropertyType("contactPhone")]
		public string ContactPhone
		{
			get { return HomePageItem.GetContactPhone(this); }
		}

		///<summary>
		/// Footer Bağlantıları
		///</summary>
		[ImplementPropertyType("footerLinks")]
		public string FooterLinks
		{
			get { return HomePageItem.GetFooterLinks(this); }
		}

		///<summary>
		/// Site Menüsü
		///</summary>
		[ImplementPropertyType("siteMenu")]
		public object SiteMenu
		{
			get { return HomePageItem.GetSiteMenu(this); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("socialFacebook")]
		public string SocialFacebook
		{
			get { return HomePageItem.GetSocialFacebook(this); }
		}

		///<summary>
		/// Google+
		///</summary>
		[ImplementPropertyType("socialGooglePlus")]
		public string SocialGooglePlus
		{
			get { return HomePageItem.GetSocialGooglePlus(this); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("socialInstagram")]
		public string SocialInstagram
		{
			get { return HomePageItem.GetSocialInstagram(this); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("socialTwitter")]
		public string SocialTwitter
		{
			get { return HomePageItem.GetSocialTwitter(this); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Repository</summary>
	[PublishedContentModel("repository")]
	public partial class Repository : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "repository";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Repository(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Repository, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>İçerik</summary>
	[PublishedContentModel("clientContentPage")]
	public partial class ClientContentPage : PublishedContentModel, IBaseContentDocType, IGalleryFolderDocType, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "clientContentPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ClientContentPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ClientContentPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Galleri
		///</summary>
		[ImplementPropertyType("pageGallery")]
		public object PageGallery
		{
			get { return this.GetPropertyValue("pageGallery"); }
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Slider Görseli</summary>
	[PublishedContentModel("carouselItem")]
	public partial class CarouselItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "carouselItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Dosya
		///</summary>
		[ImplementPropertyType("carouselImage")]
		public object CarouselImage
		{
			get { return this.GetPropertyValue("carouselImage"); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("carouselLink")]
		public object CarouselLink
		{
			get { return this.GetPropertyValue("carouselLink"); }
		}

		///<summary>
		/// Alt Başlık
		///</summary>
		[ImplementPropertyType("carouselSubTitle")]
		public string CarouselSubTitle
		{
			get { return this.GetPropertyValue<string>("carouselSubTitle"); }
		}

		///<summary>
		/// Açıklama
		///</summary>
		[ImplementPropertyType("carouselText")]
		public IHtmlString CarouselText
		{
			get { return this.GetPropertyValue<IHtmlString>("carouselText"); }
		}

		///<summary>
		/// Başlık
		///</summary>
		[ImplementPropertyType("carouselTitle")]
		public string CarouselTitle
		{
			get { return this.GetPropertyValue<string>("carouselTitle"); }
		}
	}

	/// <summary>Slider</summary>
	[PublishedContentModel("carouselFolder")]
	public partial class CarouselFolder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "carouselFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Video Galeri</summary>
	[PublishedContentModel("videoGallery")]
	public partial class VideoGallery : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "videoGallery";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VideoGallery(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VideoGallery, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Video</summary>
	[PublishedContentModel("video")]
	public partial class Video : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "video";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Video(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Video, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Açıklama
		///</summary>
		[ImplementPropertyType("aciklama")]
		public IHtmlString Aciklama
		{
			get { return this.GetPropertyValue<IHtmlString>("aciklama"); }
		}

		///<summary>
		/// Embed Kodu
		///</summary>
		[ImplementPropertyType("videoEmbedCode")]
		public string VideoEmbedCode
		{
			get { return this.GetPropertyValue<string>("videoEmbedCode"); }
		}

		///<summary>
		/// Önizleme Resmi
		///</summary>
		[ImplementPropertyType("videoPreviewImage")]
		public Umbraco.Web.Models.ImageCropDataSet VideoPreviewImage
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("videoPreviewImage"); }
		}

		///<summary>
		/// Başlık
		///</summary>
		[ImplementPropertyType("videoTitle")]
		public string VideoTitle
		{
			get { return this.GetPropertyValue<string>("videoTitle"); }
		}
	}

	/// <summary>Haber Klasörü</summary>
	[PublishedContentModel("blogFolder")]
	public partial class BlogFolder : PublishedContentModel, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return this.GetPropertyValue("pageBanner"); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Menu Ögesi</summary>
	[PublishedContentModel("mainMenuItem")]
	public partial class MainMenuItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "mainMenuItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MainMenuItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MainMenuItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link Ögesi
		///</summary>
		[ImplementPropertyType("menuLinkItem")]
		public object MenuLinkItem
		{
			get { return this.GetPropertyValue("menuLinkItem"); }
		}

		///<summary>
		/// Başlık
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return this.GetPropertyValue<string>("menuTitle"); }
		}
	}

	/// <summary>Dosya</summary>
	[PublishedContentModel("fileDocType")]
	public partial class FileDocType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fileDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FileDocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FileDocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Dosya Eki
		///</summary>
		[ImplementPropertyType("fileAttachment")]
		public string FileAttachment
		{
			get { return this.GetPropertyValue<string>("fileAttachment"); }
		}

		///<summary>
		/// Açıklama
		///</summary>
		[ImplementPropertyType("fileDescription")]
		public IHtmlString FileDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("fileDescription"); }
		}

		///<summary>
		/// Başlık
		///</summary>
		[ImplementPropertyType("fileTitle")]
		public string FileTitle
		{
			get { return this.GetPropertyValue<string>("fileTitle"); }
		}
	}

	/// <summary>Haber</summary>
	[PublishedContentModel("blogPage")]
	public partial class BlogPage : PublishedContentModel, IBaseContentDocType, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "blogPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Galleri
		///</summary>
		[ImplementPropertyType("pageGallery")]
		public object PageGallery
		{
			get { return this.GetPropertyValue("pageGallery"); }
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Proje</summary>
	[PublishedContentModel("project")]
	public partial class Project : PublishedContentModel, IBaseContentDocType, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "project";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Project(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Project, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Kategoriler
		///</summary>
		[ImplementPropertyType("categories")]
		public string Categories
		{
			get { return this.GetPropertyValue<string>("categories"); }
		}

		///<summary>
		/// topluGaleri
		///</summary>
		[ImplementPropertyType("topluGaleri")]
		public string TopluGaleri
		{
			get { return this.GetPropertyValue<string>("topluGaleri"); }
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Proje Kategorisi</summary>
	[PublishedContentModel("projectCategory")]
	public partial class ProjectCategory : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectCategory";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectCategory(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectCategory, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Kategori Adı
		///</summary>
		[ImplementPropertyType("categoryName")]
		public string CategoryName
		{
			get { return this.GetPropertyValue<string>("categoryName"); }
		}
	}

	/// <summary>Proje Kategori Liste Sayfası</summary>
	[PublishedContentModel("projectCategoryListPage")]
	public partial class ProjectCategoryListPage : PublishedContentModel, IBaseContentDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectCategoryListPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectCategoryListPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectCategoryListPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}
	}

	/// <summary>Proje Klasörü</summary>
	[PublishedContentModel("projectFolder")]
	public partial class ProjectFolder : PublishedContentModel, IBaseContentDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}
	}

	/// <summary>Servis</summary>
	[PublishedContentModel("service")]
	public partial class Service : PublishedContentModel, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "service";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Service(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Service, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner Resmi
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return this.GetPropertyValue("pageBanner"); }
		}

		///<summary>
		/// Açıklama
		///</summary>
		[ImplementPropertyType("pageDescription")]
		public IHtmlString PageDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("pageDescription"); }
		}

		///<summary>
		/// Başlık
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Hizmet Detay</summary>
	[PublishedContentModel("serviceDetail")]
	public partial class ServiceDetail : PublishedContentModel, IBaseContentDocType, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "serviceDetail";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ServiceDetail(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ServiceDetail, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>HumanResources</summary>
	[PublishedContentModel("humanResources")]
	public partial class HumanResources : PublishedContentModel, IBaseContentDocType, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "humanResources";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HumanResources(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HumanResources, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// pageGallery
		///</summary>
		[ImplementPropertyType("pageGallery")]
		public object PageGallery
		{
			get { return this.GetPropertyValue("pageGallery"); }
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Hakkımızda Kurucularımız</summary>
	[PublishedContentModel("hakkimizdaKurucularimiz")]
	public partial class HakkimizdaKurucularimiz : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hakkimizdaKurucularimiz";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HakkimizdaKurucularimiz(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HakkimizdaKurucularimiz, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// kurucufacebook
		///</summary>
		[ImplementPropertyType("kurucufacebook")]
		public string Kurucufacebook
		{
			get { return this.GetPropertyValue<string>("kurucufacebook"); }
		}

		///<summary>
		/// kurucuisim
		///</summary>
		[ImplementPropertyType("kurucuisim")]
		public string Kurucuisim
		{
			get { return this.GetPropertyValue<string>("kurucuisim"); }
		}

		///<summary>
		/// kuruculinkedin
		///</summary>
		[ImplementPropertyType("kuruculinkedin")]
		public string Kuruculinkedin
		{
			get { return this.GetPropertyValue<string>("kuruculinkedin"); }
		}

		///<summary>
		/// kurucunvan
		///</summary>
		[ImplementPropertyType("kurucunvan")]
		public string Kurucunvan
		{
			get { return this.GetPropertyValue<string>("kurucunvan"); }
		}

		///<summary>
		/// kurucuresim
		///</summary>
		[ImplementPropertyType("kurucuresim")]
		public object Kurucuresim
		{
			get { return this.GetPropertyValue("kurucuresim"); }
		}

		///<summary>
		/// kurucuyazi
		///</summary>
		[ImplementPropertyType("kurucuyazi")]
		public string Kurucuyazi
		{
			get { return this.GetPropertyValue<string>("kurucuyazi"); }
		}
	}

	/// <summary>Referans Logo</summary>
	[PublishedContentModel("referansLogo")]
	public partial class ReferansLogo : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "referansLogo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ReferansLogo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ReferansLogo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Referans Logo Başlık
		///</summary>
		[ImplementPropertyType("referansLogoBaslik")]
		public string ReferansLogoBaslik
		{
			get { return this.GetPropertyValue<string>("referansLogoBaslik"); }
		}

		///<summary>
		/// Referans Logo Link
		///</summary>
		[ImplementPropertyType("referansLogoLink")]
		public string ReferansLogoLink
		{
			get { return this.GetPropertyValue<string>("referansLogoLink"); }
		}

		///<summary>
		/// Referans Logo Resim
		///</summary>
		[ImplementPropertyType("reflogoresim")]
		public object Reflogoresim
		{
			get { return this.GetPropertyValue("reflogoresim"); }
		}
	}

	/// <summary>Anasayfa Hizmetler</summary>
	[PublishedContentModel("anasayfaHizmetler")]
	public partial class AnasayfaHizmetler : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "anasayfaHizmetler";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AnasayfaHizmetler(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AnasayfaHizmetler, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hizmet Başlık
		///</summary>
		[ImplementPropertyType("hizmetBaslik")]
		public string HizmetBaslik
		{
			get { return this.GetPropertyValue<string>("hizmetBaslik"); }
		}

		///<summary>
		/// Hizmet İçerik
		///</summary>
		[ImplementPropertyType("hizmetIcerik")]
		public string HizmetIcerik
		{
			get { return this.GetPropertyValue<string>("hizmetIcerik"); }
		}

		///<summary>
		/// Hizmet İcon
		///</summary>
		[ImplementPropertyType("hizmetIcon")]
		public string HizmetIcon
		{
			get { return this.GetPropertyValue<string>("hizmetIcon"); }
		}
	}

	/// <summary>Anasayfa Dinamik İçerik</summary>
	[PublishedContentModel("anasayfaDinamikIcerik")]
	public partial class AnasayfaDinamikIcerik : PublishedContentModel, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "anasayfaDinamikIcerik";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AnasayfaDinamikIcerik(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AnasayfaDinamikIcerik, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// banner
		///</summary>
		[ImplementPropertyType("banner")]
		public object Banner
		{
			get { return this.GetPropertyValue("banner"); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("sayfaBasligi")]
		public string SayfaBasligi
		{
			get { return this.GetPropertyValue<string>("sayfaBasligi"); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Anasayfa Proje Süreci</summary>
	[PublishedContentModel("anasayfaProjeSureci")]
	public partial class AnasayfaProjeSureci : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "anasayfaProjeSureci";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AnasayfaProjeSureci(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AnasayfaProjeSureci, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Proje Başlık
		///</summary>
		[ImplementPropertyType("projebaslik")]
		public string Projebaslik
		{
			get { return this.GetPropertyValue<string>("projebaslik"); }
		}

		///<summary>
		/// Proje İçerik
		///</summary>
		[ImplementPropertyType("projeicerik")]
		public string Projeicerik
		{
			get { return this.GetPropertyValue<string>("projeicerik"); }
		}

		///<summary>
		/// Proje ikon
		///</summary>
		[ImplementPropertyType("projeIkon")]
		public string ProjeIkon
		{
			get { return this.GetPropertyValue<string>("projeIkon"); }
		}

		///<summary>
		/// Proje Yüzde
		///</summary>
		[ImplementPropertyType("projeYuzde")]
		public int ProjeYuzde
		{
			get { return this.GetPropertyValue<int>("projeYuzde"); }
		}
	}

	/// <summary>Anasayfa Proje Yönetimi</summary>
	[PublishedContentModel("anasayfaProjeYonetimi")]
	public partial class AnasayfaProjeYonetimi : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "anasayfaProjeYonetimi";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AnasayfaProjeYonetimi(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AnasayfaProjeYonetimi, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Yönetim Başlık
		///</summary>
		[ImplementPropertyType("yonetimBaslik")]
		public string YonetimBaslik
		{
			get { return this.GetPropertyValue<string>("yonetimBaslik"); }
		}

		///<summary>
		/// Yönetim İçerik
		///</summary>
		[ImplementPropertyType("yonetimIcerik")]
		public string YonetimIcerik
		{
			get { return this.GetPropertyValue<string>("yonetimIcerik"); }
		}

		///<summary>
		/// Yönetim İkon
		///</summary>
		[ImplementPropertyType("yonetimIkon")]
		public string YonetimIkon
		{
			get { return this.GetPropertyValue<string>("yonetimIkon"); }
		}
	}

	/// <summary>Referanslar</summary>
	[PublishedContentModel("referanslar")]
	public partial class Referanslar : PublishedContentModel, IBaseContentDocType, ISeoDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "referanslar";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Referanslar(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Referanslar, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// İçerik
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return BaseContentDocType.GetContentText(this); }
		}

		///<summary>
		/// Listelenecek Komşular Ögesi: Sayfanın detayında, sağ tarafta listelenen ögelerin okunacağı root
		///</summary>
		[ImplementPropertyType("neighbourWidgetRoot")]
		public object NeighbourWidgetRoot
		{
			get { return BaseContentDocType.GetNeighbourWidgetRoot(this); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("pageBanner")]
		public object PageBanner
		{
			get { return BaseContentDocType.GetPageBanner(this); }
		}

		///<summary>
		/// Sayfa Resmi
		///</summary>
		[ImplementPropertyType("pageImage")]
		public object PageImage
		{
			get { return BaseContentDocType.GetPageImage(this); }
		}

		///<summary>
		/// Yayınlama Tarihi
		///</summary>
		[ImplementPropertyType("pagePublishDate")]
		public DateTime PagePublishDate
		{
			get { return BaseContentDocType.GetPagePublishDate(this); }
		}

		///<summary>
		/// Alt başlık
		///</summary>
		[ImplementPropertyType("pageSubTitle")]
		public string PageSubTitle
		{
			get { return BaseContentDocType.GetPageSubTitle(this); }
		}

		///<summary>
		/// Sayfa Başlığı
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return BaseContentDocType.GetPageTitle(this); }
		}

		///<summary>
		/// Önyazı
		///</summary>
		[ImplementPropertyType("previewText")]
		public string PreviewText
		{
			get { return BaseContentDocType.GetPreviewText(this); }
		}

		///<summary>
		/// Yönlendirme
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public object UmbracoRedirect
		{
			get { return BaseContentDocType.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Tarayıcı Başlığı
		///</summary>
		[ImplementPropertyType("browserTitle")]
		public string BrowserTitle
		{
			get { return SeoDocType.GetBrowserTitle(this); }
		}

		///<summary>
		/// Meta Tanımlama
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return SeoDocType.GetMetaDescription(this); }
		}

		///<summary>
		/// Etiketler
		///</summary>
		[ImplementPropertyType("metaTags")]
		public object MetaTags
		{
			get { return SeoDocType.GetMetaTags(this); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
